### ISSUE TITLE
不妊治療当事者へのアンケートの実施についての議論

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/create-docs#1]
- 不妊治療当事者へのアンケートの実施 (Xで3パターンのうちどれがいいか聞く)
- そもそも何をアンケートで聞くかとかX上のツイートの文面についてこのissue上で議論する。
- ツイート案
   - TBD

**Comment by sunmoonStern** [comment]
プロトタイプとして現状存在するものは3つ。
- prototype-k https://code-for-future-moms.github.io/prototype-k/
- prototype-k2 https://code-for-future-moms.github.io/prototype-k/k2/
- prototype-s https://code-for-future-moms.github.io/prototype-s/

アンケートをするときはこの中で一番よいと思うもの選んで、って感じで３択にしてよいか。それともk2とsとの2択?

**Comment by ktakayama** [comment]
kもいい〜という意見もあるようなので、3つあってもいいかもですね
それぞれに違いがあるし細かいところまで揃えてない部分あるので「kのここが良くて、sのここがいい」みたいなコメントがもらえると参考になるかもです

**Comment by yorusuke** [comment]
私の感覚だと、kとsかなという印象です！
ただ、スマホのみなのでPCだと見え方が違うかもしれません🙇‍♂️

ひとまず転記します！

**Comment by sunmoonStern** [comment]
コメント下さった方ありがとうございます 🙇🏼‍♀️ 
当初はパターン1, 2, 3のどれがいいかを集計するためにXの投票機能を使おうと思っていましたが

> 「kのここが良くて、sのここがいい」みたいなコメントがもらえると参考になるかも

ということなのでGoogle Formsで回答フォーム作った方がいいかもなあ

**Comment by ktakayama** [comment]
投票された件数だけみても、なぜそれがいいと思ったのかわからないと結局どうしたらいいかわからないのかなと思いまして
回答結構多く集まりそうですか？
メンションしてください〜っていう形式でもいいのかなと思います
手軽な感じだし

**Comment by sunmoonStern** [comment]
うーん、一般人なのですごくフォロワーが多いわけじゃないです。不妊治療アカウントは現在128人フォロワーがいて、
不妊治療卒業したタイミングでフォロー解除する人も多いから、実際に治療中はもう少しいたと思いますが、
その際にほそぼそと東京都の医療機関の可視化を(github pagesにすらしてなくて)codepenにあげたときには、50か60かviewがついたから、治療成績比較サイト作りました！ってツイートして、みてくれる人はそれなりにいるんじゃないかと期待しています。
1. リンク踏んでみてくれる < 2. Xで投票してくれる < 3. Googleフォームに回答してくれる or メンションしてコメントくれる
の順に大変さがあがっていくと思うから、当初は2にして回答する人の負担を軽くして数集めようと思ったけど、3にしないと開発の参考になるFBが得られないならそうしようかと 🤔

**Comment by sunmoonStern** [comment]
# 新たなprototypeの提案

まだgithub pagesにできていませんが、prototype-k2かprototpye-sの、横並びにだーっとクリニック並んでいる方の可視化で、エリアによるチェックボックスで絞り込みするプロトタイプを作ってアンケートの選択肢に加えるのはどうでしょうか?

まだHighCharts部分は作れていないのですが、こんな感じで。
https://codepen.io/sunmoonstern/pen/xxmwxrG

**Comment by ktakayama** [comment]
@sunmoonStern 
> 横並びにだーっとクリニック並んでいる方の可視化で、エリアによるチェックボックスで絞り込みするプロトタイプ

良いと思います！
私も最終的には都道府県レベルでは絞り込みはあったほうがいいかなと思っています。

アンケートについては、そんなにたくさんコメントが欲しいわけではないので、投票+コメントある人はメンションなりしてください、くらいの感じで数件来たらいいかなくらいに思ってました。

**Comment by sunmoonStern** [comment]
> 投票+コメントある人はメンションなりしてください、くらいの感じで数件来たらいいかな

たしかにそれが実施する方もラクなので、採用 👍🏼

**Comment by ktakayama** [comment]
グラフ2種類入れたパターンを作ってみたくて作りました。表示してる内容はprototype-sと同じなんですが💦
テーブルはなくてもいいかもなーと思ってテーブルは消したんですが、あんまりプロトタイプが多いと投票が分散しちゃうので、新しく作ったやつは住所やグラフ内のツールチップも充実できているので、テーブル復活させて他にも調整してprototype-sのかわりにしちゃうのもありなのかもしれないです。


https://github.com/code-for-future-moms/prototype-k/pull/35
https://code-for-future-moms.github.io/prototype-k/k3/

**Comment by ktakayama** [comment]
k3に入れたかった住所のフィルタリングを追加できました
今日はもう作業時間取れるかわからないので、いったん区切りになりそうです

**Comment by sunmoonStern** [comment]
@ktakayama もろもろ対応本当にありがとうございます 😄 

k3に住所フィルタリングが入ったらk4いらないから3択にしようかなと考えたものの、
住所フィルタリングするのがグラフの上か下かが結構思想に違いがありそうなのと、現行の"▼ 表示地域：すべて"で
初見でクリックできると気付けるか自信がないのでk4残して4択にしようかと思っています。

**Comment by sunmoonStern** [comment]
昨日の夜中から投票開始していますが全然回答あつまらん 😓

**Comment by ktakayama** [comment]
😭

**Comment by sunmoonStern** [comment]
結局プロトタイプk, k2, k3, k4の4択で投票を実施したところ、2票しか回答集まらず。
k 1票、k2 1票という結果になりました。
Takayamaさんが聞いてきたコメントもkがよいということだったのでprototype-kっぽい見た目に寄せることに。

**Comment by sunmoonStern** [comment]
closeしてあとでmarkdownで記録しておく。より多くのFBのもらい方は課題である...
