### ISSUE TITLE
より多くの不妊治療当事者から良質なFBをもらう方法についてのアイデア出し 

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/create-docs#2]
- 思いつく方法をとりあえず列挙
   - 不妊治療の有名どころのアカウントにメールやDMなどで個別に連絡を取って、X上の投票だったりGoogle Formsへの回答を促してもらうようにお願いする
   - 体外受精を行っている個別のクリニックに電話やメールをして、院内の患者向けの掲示板に投票するページへのQRコードなどを貼ってもらうよう頼む
   - 私の地元の代議士さんに拡散してもらうよう頼む
      - 不妊治療を予定している人/治療中の人にどれだけリーチできるかは不明
   - 前回はX(Twitter)だけで投票を実施したが、Google Formsで回答してもらってURL自体はX, Facebook, Instagramなど各種SNSで宣伝する

**Comment by sunmoonStern** [comment]
どれもそこそこ大変そうだなあ...
この中では3つ目が比較的やりやすそう。すでにある程度の信頼関係ができているので。
1つ目2つ目も電話かけるのは結構心理的なハードル高いけどメール送ったりネット上で完結するだけのダメ元で数うちゃ当たる方式でメール送ったりするだけならできるかも...

**Comment by sunmoonStern** [comment]
前回のX上の投票は、文字数制限のため、実際にプロトタイプが見られるURLリンクを投票のツイート本文に貼れなくて、
スレッドを辿らないとプロトタイプが見られないのもよくなかったかも。

**Comment by sunmoonStern** [comment]
次FBをもらうときはX(Twitter)に限らず、Facebookでも聞いてみる

**Comment by sunmoonStern** [comment]
フォロワーに多数の不妊治療当事者がいると思われる不妊治療マンガをX上で発表されている方に拡散に協力いただけないかメールを書いてみた。

**Comment by ktakayama** [comment]
LINEオープンチャットとか使えないかなと思って検索してみたけど、すでに治療中の方も多いだろうからそこに入り込むのは結構勇気がいりそうですね、、

**Comment by sunmoonStern** [comment]
LINEオプチャいいかも！地域の子育てオプチャに入っているけど、研究用途で子育てにおける課題をアンケートしてた人もいたから、これから不妊治療とか体外受精の交換用のLINEオプチャを探して入って聞けばいいし、なんなら自分が通っていたクリニック通院者の小規模な非公式オプチャを自分が作ってたから、そこでも聞けばいいですわ。なんで思いつかなかったんだろ。

**Comment by sunmoonStern** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSfNex46vK31zEkD2YcH9wan4hozyvLiv08WcmBKKEYjs62Yhg/viewform?usp=sf_link にお試しでGoogleフォーム作ってみた。こんな感じでFBを集めたい。
どのプロトタイプが一番いいかの設問でどのプロトタイプを選択肢に含めるかは決めなければいけない。ただあまり選択肢を増やすと回答者の負担が増えるので選択肢数は3個以下にしたい。

**Comment by sunmoonStern** [comment]
@ktakayama 現状、アンケートで選択肢にするのはk3とk5の2択でしょうか? 他にTakayamaさんご家族のFB https://github.com/code-for-future-moms/prototype-k/issues/52#issuecomment-1738389652 を反映した選択肢も作成しますか?
現状全国版のデータがいつで回るかわからないのですが、東京都プロトタイプのアンケート実施は数日中にも実施したくて、
具体的な選択肢の検討を進めたいです。縦向き横向きとか少しのデザイン変更なら自分も対応できると思うので。

**Comment by ktakayama** [comment]
@sunmoonStern
プロトタイプに関してはk5ベースで行く方向で考えてらっしゃるのかなと思っておりましたので、次のアンケートではk5についての意見を聞いたりするのかと思っていました。
例えば「ここがわかりにくかった、ここをもっとこうして欲しい」など。

プロトタイプの種類を選ぶなら、そうですね、k3,k5とかですかね。
グラフの横向きについては、いったん対応しないままでいいかもしんないです。
k3にせよk5にせよ、今後グラフを横向きにする可能性は高そうなので、どっちかだけ横向きに対応しちゃうとアンケートに答える際の判断基準に入っちゃいそうだからもったいないのかなと。

**Comment by sunmoonStern** [comment]
@ktakayama たしかに、複数のプロトタイプでやるよりシンプルにk5に対する意見を聞くようにしましょうか。
今回のアンケート実施前に横向きの件は対応しない旨承知です。

**Comment by sunmoonStern** [comment]
大人数の不妊治療している人用のLINEオプチャ参加承認がおりない、不妊治療マンガ家さんからも返信はないが、
折れずに明日深夜にGoogleフォームを書いたSNSを投下したいと思います。
**追記: [Googleフォーム](https://docs.google.com/forms/d/e/1FAIpQLSfNex46vK31zEkD2YcH9wan4hozyvLiv08WcmBKKEYjs62Yhg/viewform?usp=sf_link)はk5のみへの意見を聞くように修正しました。**

**Comment by sunmoonStern** [comment]
500人くらいメンバーがいる不妊治療オプチャに参加させてもらえました。このオプチャは夜中は投稿禁止なので本日夜9-11時ごろ投稿予定です。

- やること
   - [x] 大規模LINEオプチャへの投稿 
   - [x] 自分がオーナーの小規模LINEオプチャへの投稿 
   - [x] slackでつながっている友達への共有
   - [x] FBへの投稿
   - [x] Xへの投稿
   - [ ] Instagramへの投稿

**Comment by sunmoonStern** [comment]
今回も今のところまだ2件しか回答集まってなくて泣ける 😢 
やはり素人が拡散しようと思っても限界が

**Comment by sunmoonStern** [comment]
とりあえず議員さんにも拡散いただきましたが回答数は増えず。
